package org.powerbot.bot;

public enum EventType {
	MESSAGE_EVENT, MODEL_RENDER_EVENT, PAINT_EVENT, TEXT_PAINT_EVENT,
	MOUSE_EVENT, MOUSE_MOTION_EVENT, MOUSE_WHEEL_EVENT, FOCUS_EVENT,
	KEY_EVENT, DO_ACTION_EVENT, INVENTORY_CHANGE_EVENT, GAME_TICK_EVENT,
	UPDATE_NPCS_EVENT, SCRIPT_STATE_CHANGED_EVENT;

	public int id() {
		return ordinal();
	}
}
